### PR TITLE
Fix exception handling in NextcloudClient

### LINKED ISSUE #393: NextcloudClient ignores exceptions
It looks like exception handling in `NextcloudClient.execute()` is not implemented at all. This causes the client to fail due to unhandled exceptions due to random, genuine and expected network errors.

Related issues:

nextcloud/android#5245
nextcloud/android#5305
nextcloud/android#5310
nextcloud/android#5331
nextcloud/android#5333

### PR DESCRIPTION
**Pull request by ezaquarii**
Fixes #393
Fixes nextcloud/android#5245
Fixes nextcloud/android#5305
Fixes nextcloud/android#5310
Fixes nextcloud/android#5331
Fixes nextcloud/android#5333
Fixes nextcloud/android#5390

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

### CODE REVIEW

File: src/main/java/com/nextcloud/common/NextcloudClient.kt [hunk 1]
```diff
@@ -50,40 +47,47 @@ import javax.net.ssl.SSLSession
...
+        } catch (ex: Exception) {
+            RemoteOperationResult(ex)
+        }
     }
     
     fun execute(method: OkHttpMethodBase): Int {
         return method.execute(this)
     }
 
+    @Throws(IOException::class)
```
Comment (ezaquarii) [inline src/main/java/com/nextcloud/common/NextcloudClient.kt]: @tobiasKaminsky This will proably break clients, but since `IOException` is checked, it must be handled.
There is no API to return valid `Response` in case of error, as `OkHttp3` use exceptions to signal abnormal condition. We should follow.

File: src/main/java/com/nextcloud/common/NextcloudClient.kt [hunk 2]
```diff
@@ -50,40 +47,47 @@ import javax.net.ssl.SSLSession
 import javax.net.ssl.TrustManager
 
 
-class NextcloudClient(var baseUri: Uri, val context: Context) {
+class NextcloudClient(var baseUri: Uri, val context: Context, client: OkHttpClient) {
     lateinit var credentials: String
```
Comment (ezaquarii) [inline src/main/java/com/nextcloud/common/NextcloudClient.kt]: Misused `lateinit`. This should be initialized here. I'll open another ticket for this, tho.

**Comment by ezaquarii** [comment]
@tobiasKaminsky Could you pealse check the method annotated with @Throws? I won't have bandwidth to do it now.

File: src/main/java/com/nextcloud/common/NextcloudClient.kt (hunk 1 above)
Comment (tobiasKaminsky) [reply src/main/java/com/nextcloud/common/NextcloudClient.kt]: Hm. I would go instead with try/catch so that we can return our own error code.
After all, this is in our library and also should only be called within the library.

File: src/main/java/com/nextcloud/common/NextcloudClient.kt (hunk 2 above)
Comment (tobiasKaminsky) [reply src/main/java/com/nextcloud/common/NextcloudClient.kt]: This is fixed via #396

File: src/main/java/com/nextcloud/common/NextcloudClient.kt (hunk 1 above)
Comment (ezaquarii) [reply src/main/java/com/nextcloud/common/NextcloudClient.kt]: I wrapped the exception in a union-like object.

File: src/main/java/com/nextcloud/common/NextcloudClient.kt [hunk 3]
```diff
@@ -50,42 +47,58 @@ import javax.net.ssl.SSLSession
...
     lateinit var userId: String
     lateinit var request: Request
     var followRedirects = true;
-    val client: OkHttpClient
+    val client = client
+
+    data class ResponseOrError private constructor(val result: Response?, val error: Exception?) {
```
Comment (tobiasKaminsky) [inline src/main/java/com/nextcloud/common/NextcloudClient.kt]: Nice approach :+1: 
To not have too many things in one class, can we extract this into its own class?

**Comment by ezaquarii** [comment]
Go ahead - I don't mind. It would be speedier if you can do it yourself in another commit in this branch as I can't work on it today due to work related schedule 

BTW, while being here, could you please mark internal interfaces with a keyword internal? This would make them unavailable outside library code (whole library, not a package; internal works a bit differently from Java's package private).

The subtle difference is:
Package private - inside the package only.
Internal - access in whole compilation unit, which in this case is nextcloud-android-library project, but not in nextcloud-android app.

By marking things internal, we can safely refactor inside the library boundaries, without risk of breaking library users that might be using our private-but-still-bublic APIs.

Cheers,
Chris

File: src/main/java/com/nextcloud/common/NextcloudClient.kt (hunk 3 above)
Comment (ezaquarii) [reply src/main/java/com/nextcloud/common/NextcloudClient.kt]: extracted

**Comment by ezaquarii** [comment]
@tobiasKaminsky I made the `okhttp3` `execute()` request internal. Please confirm if this is what we can do, ie. we don't plan to use it outside the library.

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky I made the `okhttp3` `execute()` request internal. Please confirm if this is what we can do, ie. we don't plan to use it outside the library.

Should be fine, I currently cannot imagine why we need this outside our lib, but we can still change it later, if required.
